class AudiosList{

  List<String> familuAudios=[
    'assets/audios/family_audios/Umndeni.mp3',
    'assets/audios/family_audios/Umkhulu.mp3',
    'assets/audios/family_audios/ugogo.mp3',
    'assets/audios/family_audios/ubaba.mp3',
    'assets/audios/family_audios/umama.mp3',
    'assets/audios/family_audios/umtwana.mp3',
    'assets/audios/family_audios/Abantwana.mp3',
    'assets/audios/family_audios/UdadewethuUsisi.mp3',
    'assets/audios/family_audios/UmfowethuUbhuti.mp3',
    'assets/audios/family_audios/umfowethuomdala.mp3',
    'assets/audios/family_audios/umfowethuomncani.mp3',
    'assets/audios/family_audios/umzala.mp3',
    'assets/audios/family_audios/Ubabaomkhulu.mp3',
    'assets/audios/family_audios/Umalume.mp3',
    'assets/audios/family_audios/u-anti.mp3',
    'assets/audios/family_audios/umalumekazi.mp3',
    'assets/audios/family_audios/abazali.mp3',


  ];

  List pronounsAudios=[
    "assets/audios/pronouns/mina.mp3",
    "assets/audios/pronouns/wena.mp3",
    "assets/audios/pronouns/Yena.mp3",
    "assets/audios/pronouns/Thina.mp3",
    "assets/audios/pronouns/Nina.mp3",
    "assets/audios/pronouns/Bona.mp3"  ,
    "assets/audios/pronouns/Akekho.mp3",
    "assets/audios/pronouns/Okwami.mp3",
    "assets/audios/pronouns/Umuntu.mp3",
    "assets/audios/pronouns/Leyo.mp3",
    "assets/audios/pronouns/Mbalwa.mp3",
    "assets/audios/pronouns/WonkeUmuntu.mp3"  ,
    "assets/audios/pronouns/Utho.mp3",
    "assets/audios/pronouns/Akho.mp3",
    "assets/audios/pronouns/Zazo.mp3",
    "assets/audios/pronouns/Lutho.mp3",

  ];
  List colorsAudios=[
    "assets/audios/colors/Mhlophe.mp3",
    "assets/audios/colors/Mnyama.mp3",
    "assets/audios/colors/Nsomi.mp3",
    "assets/audios/colors/Hlaza.mp3",
    "assets/audios/colors/Phuzi.mp3",
    "assets/audios/colors/Bomvu.mp3",
    "assets/audios/colors/Phinki.mp3"
  ];
  List timeAudios=[
    "assets/audios/time/Namlhanje.mp3",
    "assets/audios/time/Izolo.mp3",
    "assets/audios/time/Kusasa.mp3",
    "assets/audios/time/Ekuseni.mp3",
    "assets/audios/time/Mtambama.mp3",
    "assets/audios/time/Ebusuku.mp3",
    "assets/audios/time/Amasontoambalwa.mp3",
    "assets/audios/time/Kulelisonto.mp3",
    "assets/audios/time/Isontoelidlule.mp3",
    "assets/audios/time/Isontoelizayo.mp3",
    "assets/audios/time/Kulonyaka.mp3",
    "assets/audios/time/Ngonyakaodlule.mp3",
    "assets/audios/time/Ngonyakaozayo.mp3",
    "assets/audios/time/Kulenyanga.mp3",
    "assets/audios/time/Okwamanje.mp3",
    "assets/audios/time/Emvakweskhathi.mp3",
    "assets/audios/time/Ngaphambikweskhathi.mp3",

  ];
  List daysAudios=[
    "assets/audios/days/Umsumbuluko.mp3",
    "assets/audios/days/Ulwesibili.mp3",
    "assets/audios/days/Ulwesithathu.mp3",
    "assets/audios/days/Ulwesine.mp3",
    "assets/audios/days/Ulwesihlanu.mp3",
    "assets/audios/days/Umgqibelo.mp3",
    "assets/audios/days/Isonto.mp3"
  ];
  List itemsAudios=[
    "assets/audios/items/Itafula.mp3",
    "assets/audios/items/Isitulo.mp3",
    "assets/audios/items/Ipuleti.mp3",
    "assets/audios/items/Izicathulo.mp3",
    "assets/audios/items/Ipensele.mp3",
    "assets/audios/items/Incwadi.mp3",
    "assets/audios/items/Isikhwama.mp3",
    "assets/audios/items/Inkomishi.mp3",
    "assets/audios/items/Isipuni.mp3",
    "assets/audios/items/Ummese.mp3",
    "assets/audios/items/Umshanelo.mp3",
    "assets/audios/items/Umbede.mp3",
    "assets/audios/items/Ingubo.mp3",
    "assets/audios/items/Izingubo.mp3",
    "assets/audios/items/Ibulukwe.mp3",

    "assets/audios/items/Ipeni.mp3",
    "assets/audios/items/Ifasitela.mp3",
    "assets/audios/items/Umnyango.mp3",
  ];
  List placesAudios=[
    "assets/audios/places/Izindawo.mp3",
    "assets/audios/places/Indlu.mp3",
    "assets/audios/places/Ikilasi.mp3",
    "assets/audios/places/Iposi.mp3",
    "assets/audios/places/Isonto.mp3",
    "assets/audios/places/Umfula.mp3",
    "assets/audios/places/Umtholampilo.mp3",
    "assets/audios/places/Isitolo.mp3",
    "assets/audios/places/Insimu.mp3",
    "assets/audios/places/Ithoyilethi.mp3",
    "assets/audios/places/Ikhishi.mp3",
    "assets/audios/places/Isikole.mp3",
    "assets/audios/places/Isibhedlela.mp3",
    "assets/audios/places/Ibhange.mp3"
  ];

  List foodAudios=[
    "assets/audios/foods/Ukudla.mp3",
    "assets/audios/foods/Ushukela.mp3",
    "assets/audios/foods/Usawoti.mp3",
    "assets/audios/foods/Amanzi.mp3",
    "assets/audios/foods/Amabele.mp3",
    "assets/audios/foods/Impupu.mp3",
    "assets/audios/foods/Ubisi.mp3",
    "assets/audios/foods/Utamatisi.mp3",
    "assets/audios/foods/Amazambane.mp3",
    "assets/audios/foods/Amaqanda.mp3",
    "assets/audios/foods/Isinkwa.mp3",
    "assets/audios/foods/Ikhofi.mp3",
    "assets/audios/foods/Itiye.mp3",
    "assets/audios/foods/Umdokwe.mp3",
    "assets/audios/foods/U-anyanyisi.mp3",
    "assets/audios/foods/I-olitshi.mp3",
    "assets/audios/foods/I-apula.mp3",
    "assets/audios/foods/Amakinati.mp3",
    "assets/audios/foods/Ubhotshisi.mp3",
  ];

  List numbersAudios=[
    "assets/audios/numbers/Kunye.mp3",
    "assets/audios/numbers/Kubili.mp3",
    "assets/audios/numbers/Kuthathu.mp3",
    "assets/audios/numbers/Kune.mp3",
    "assets/audios/numbers/Kuhlanu.mp3",
    "assets/audios/numbers/Isithupha.mp3",
    "assets/audios/numbers/Isikhombisa.mp3",
    "assets/audios/numbers/Isishiyagalombili.mp3",
    "assets/audios/numbers/Isishiyagalolunye.mp3",
    "assets/audios/numbers/Ishumi.mp3",
    "assets/audios/numbers/Ishumi1.mp3",
    "assets/audios/numbers/Ishumi2.mp3",
    "assets/audios/numbers/Ishumi3.mp3",
    "assets/audios/numbers/Ishumi4.mp3",
    "assets/audios/numbers/Ishumi5.mp3",
    "assets/audios/numbers/Ishumi6.mp3",
    "assets/audios/numbers/Ishumi7.mp3",
    "assets/audios/numbers/Ishumi8.mp3",
    "assets/audios/numbers/Ishumi9.mp3",
    "assets/audios/numbers/Amashumiamabili.mp3"
  ];
  List conjuctionsAudios=[
    "assets/audios/conjuctions/Na.mp3",
    "assets/audios/conjuctions/Kodwa.mp3",
    "assets/audios/conjuctions/Noma.mp3",
    "assets/audios/conjuctions/Njenga.mp3",
    "assets/audios/conjuctions/Ngakhoke.mp3",
    "assets/audios/conjuctions/Ngoba.mp3",
    "assets/audios/conjuctions/Kwazekwa.mp3",
    "assets/audios/conjuctions/Kamuva.mp3",
    "assets/audios/conjuctions/Ngaphandle.mp3",
    "assets/audios/conjuctions/Kuphela.mp3",
    "assets/audios/conjuctions/Khona.mp3",
    "assets/audios/conjuctions/Kanye.mp3",
    "assets/audios/conjuctions/Phambili.mp3",
    "assets/audios/conjuctions/Noba.mp3",
    "assets/audios/conjuctions/Manje.mp3",
    "assets/audios/conjuctions/Selokhu.mp3",
    "assets/audios/conjuctions/Nokho.mp3",
    "assets/audios/conjuctions/Futhi.mp3",

  ];

  List bodyPartsAudios=[
    "assets/audios/body_parts/Ikhanda.mp3",
    "assets/audios/body_parts/Uboya.mp3",
    "assets/audios/body_parts/Ihlo.mp3",
    "assets/audios/body_parts/Indlebe.mp3",
    "assets/audios/body_parts/Isihlati.mp3",
    "assets/audios/body_parts/Umlomo.mp3",
    "assets/audios/body_parts/Ikhala.mp3",
    "assets/audios/body_parts/Umhlathi.mp3",
    "assets/audios/body_parts/Intamo.mp3",
    "assets/audios/body_parts/Igxalaba.mp3",
    "assets/audios/body_parts/Indololwane.mp3",
    "assets/audios/body_parts/Isandla.mp3",
    "assets/audios/body_parts/Umunwe.mp3",
    "assets/audios/body_parts/Imbhokisi.mp3",
    "assets/audios/body_parts/Ukhalo.mp3",
    "assets/audios/body_parts/Hlomisa.mp3",
    "assets/audios/body_parts/Isisu.mp3",
    "assets/audios/body_parts/Idolo.mp3",
    "assets/audios/body_parts/Unyawo.mp3",
    "assets/audios/body_parts/Izwane.mp3",
    "assets/audios/body_parts/Ithende.mp3",

  ];
}